desc customers;

select customer# from customers;

select customer#, firstname, lastname from customers;

select customer#, lastname, firstname from customers;

SELECT CUSTOMER# AS "CUST-N0" ,
LASTNAME "LAST NAME",
FIRSTNAME "FIRST NAME",
ADDRESS ,
CITY ,
ZIP  FROM customers;
-- COLUMN ALLIASING ( RENAMING NAME TEMPORARILY ) USING AS AND DOUBLE QUOTATIONS

DESC CUSTOMERS;
SELECT ORDER#, CUSTOMER#, SHIPCOST, SHIPCOST+5*2 MU_SHIPCOST, SHIPCOST+5 ADD_COST FROM ORDERS;


-- ARITHMETIC OPERATIONS IN THE DATABASE
SELECT TITLE, RETAIL, COST, COST*RETAIL AS TOTALPRICE FROM BOOKS;

SELECT * FROM CUSTOMERS;
-- USING DISTINCT
SELECT DISTINCT STATE FROM CUSTOMERS;

--CONCATENATION, JOINGING TWO COLUMNS, USING PIPESIGN || ' ' ||
SELECT * FROM CUSTOMERS;

SELECT FIRSTNAME || ', ' ||LASTNAME AS FULLNAME FROM CUSTOMERS;

SELECT * 
FROM CUSTOMERS
WHERE