--question 1    //comp122 301242419 Carl Kevin Gasal
SELECT LASTNAME, FIRSTNAME, STATE
FROM CUSTOMERS
WHERE STATE = 'NJ';

--question 2    //comp122 301242419 Carl Kevin Gasal
SELECT ORDER#, SHIPDATE
FROM ORDERS
WHERE SHIPDATE > '2009-04-01';

--question 3    //comp122 301242419 Carl Kevin Gasal
SELECT TITLE, CATEGORY
FROM Books
WHERE CATEGORY != 'FITNESS';

--question 4 A   //comp122 301242419 Carl Kevin Gasal
SELECT CUSTOMER#, LASTNAME, STATE
FROM Customers
WHERE STATE = 'GA' OR STATE = 'NJ'
ORDER BY LASTNAME ASC;
--question 4 B   //comp122 301242419 Carl Kevin Gasal
SELECT CUSTOMER#, LASTNAME, STATE
FROM Customers
WHERE STATE = 'GA' OR STATE = 'NJ'
ORDER BY LASTNAME ASC;

--question 5 A   //comp122 301242419 Carl Kevin Gasal
SELECT ORDER#, ORDERDATE
FROM Orders
WHERE ORDERDATE <= '2009-04-01'

--question 5 B   //comp122 301242419 Carl Kevin Gasal
SELECT ORDER#, ORDERDATE
FROM Orders
WHERE ORDERDATE BETWEEN '2009-03-01' AND '2009-04-01'

--question 6    //comp122 301242419 Carl Kevin Gasal
SELECT LNAME, FNAME
FROM AUTHOR
WHERE LNAME LIKE '%IN%'
ORDER BY LNAME ASC, FNAME ASC;

--question 7    //comp122 301242419 Carl Kevin Gasal
SELECT C1.LASTNAME, C2.CUSTOMER#
FROM CUSTOMERS C1
JOIN CUSTOMERS C2 ON C1.REFERRED = C2.CUSTOMER#
WHERE C1.REFERRED IS NOT NULL;

--question 8 A.   //comp122 301242419 Carl Kevin Gasal
SELECT TITLE, CATEGORY
FROM BOOKS
WHERE CATEGORY LIKE '%CHILDREN%' OR CATEGORY LIKE '%COOKING%';

SELECT TITLE, CATEGORY
FROM BOOKS
--question 8 B.   //comp122 301242419 Carl Kevin Gasal
SELECT TITLE, CATEGORY
FROM BOOKS
WHERE CATEGORY = 'CHILDREN' OR CATEGORY = 'COOKING';

--question 8 C.   //comp122 301242419 Carl Kevin Gasal
SELECT TITLE, CATEGORY
FROM BOOKS
WHERE CATEGORY IN ('CHILDREN', 'COOKING');

--question 9    //comp122 301242419 Carl Kevin Gasal
SELECT ISBN, TITLE
FROM BOOKS
WHERE TITLE LIKE '_A%N%'
ORDER BY TITLE DESC;

--question 10 A   //comp122 301242419 Carl Kevin Gasal
SELECT TITLE, PUBDATE
FROM BOOKS
WHERE CATEGORY = 'COMPUTER' AND PUBDATE BETWEEN '05-01-01' AND '05-12-31';

--question 10 B   //comp122 301242419 Carl Kevin Gasal
SELECT TITLE, PUBDATE
FROM BOOKS
WHERE CATEGORY = 'COMPUTER' AND PUBDATE >= '05-01-01' AND PUBDATE <= '05-12-31';

--question 10 C   //comp122 301242419 Carl Kevin Gasal
SELECT TITLE, PUBDATE
FROM BOOKS
WHERE CATEGORY = 'COMPUTER' AND PUBDATE LIKE '%05%';

--HANDS-ON 1:A TRADITIONAL APPROACH  //COMP122 301242419 CARL KEVIN GASAL
SELECT b.TITLE, p.CONTACT, p.PHONE
FROM BOOKS b, PUBLISHER p
WHERE b.PUBID = p.PUBID;

--HANDS-ON 1:B JOIN KEYWORD APPROACH //COMP122 301242419 CARL KEVIN GASAL
SELECT b.TITLE, p.CONTACT, p.PHONE
FROM BOOKS b
JOIN PUBLISHER p ON b.PUBID = p.PUBID;

--HANDS-ON 2:A TRADITIONAL APPROACH  //COMP122 301242419 CARL KEVIN GASAL
SELECT ORDERS.ORDER#, CUSTOMERS.FIRSTNAME || ' ' ||
        CUSTOMERS.LASTNAME AS CUSTOMER_NAME, ORDERS.ORDERDATE
FROM ORDERS, CUSTOMERS
WHERE ORDERS.CUSTOMER# = CUSTOMERS.CUSTOMER#
AND ORDERS.SHIPDATE IS NULL
ORDER BY ORDERS.ORDERDATE;

--HANDS-ON 2:B JOIN KEYWORD APPROACH //COMP122 301242419 CARL KEVIN GASAL
SELECT ORDERS.ORDER#, CUSTOMERS.FIRSTNAME || ' ' ||
        CUSTOMERS.LASTNAME AS CUSTOMER_NAME, ORDERS.ORDERDATE
FROM ORDERS
JOIN CUSTOMERS ON ORDERS.CUSTOMER# = CUSTOMERS.CUSTOMER#
WHERE ORDERS.SHIPDATE IS NULL
ORDER BY ORDERS.ORDERDATE;

--HANDS-ON 3:A TRADITIONAL APPROACH  //COMP122 301242419 CARL KEVIN GASAL
SELECT c.LASTNAME, c.FIRSTNAME
FROM CUSTOMERS c, ORDERS o, ORDERITEMS oi, BOOKS b
WHERE c.CUSTOMER# = o.CUSTOMER#
AND o.ORDER# = oi.ORDER#
AND oi.ISBN = b.ISBN
AND c.STATE = 'FL'
AND b.CATEGORY = 'COMPUTER';

--HANDS-ON 3:B JOIN KEYWORD APPROACH //COMP122 301242419 CARL KEVIN GASAL
SELECT c.LASTNAME, c.FIRSTNAME
FROM CUSTOMERS c
JOIN ORDERS o ON c.CUSTOMER# = o.CUSTOMER#
JOIN ORDERITEMS oi ON o.ORDER# = oi.ORDER#
JOIN BOOKS b ON oi.ISBN = b.ISBN
WHERE c.STATE = 'FL'
AND b.CATEGORY = 'COMPUTER';

--HANDS-ON 4:A TRADITIONAL APPROACH  //COMP122 301242419 CARL KEVIN GASAL
SELECT DISTINCT b.TITLE
FROM ORDERS o, ORDERITEMS oi, BOOKS b, CUSTOMERS c
WHERE o.ORDER# = oi.ORDER#
AND oi.ISBN = b.ISBN
AND o.CUSTOMER# = c.CUSTOMER#
AND c.LASTNAME = 'LUCAS'
AND c.FIRSTNAME = 'JAKE';

--HANDS-ON 4:B JOIN KEYWORD APPROACH //COMP122 301242419 CARL KEVIN GASAL
SELECT DISTINCT b.TITLE
FROM ORDERS o
JOIN ORDERITEMS oi ON o.ORDER# = oi.ORDER#
JOIN BOOKS b ON oi.ISBN = b.ISBN
JOIN CUSTOMERS c ON o.CUSTOMER# = c.CUSTOMER#
WHERE C.LASTNAME = 'LUCAS'
AND C.FIRSTNAME = 'JAKE';

--HANDS-ON 5:A TRADITIONAL APPROACH  //COMP122 301242419 CARL KEVIN GASAL
SELECT O.ORDERDATE, I.ISBN, I.QUANTITY, (I.PAIDEACH - B.COST) * I.QUANTITY AS PROFIT
FROM ORDERS O, ORDERITEMS I, BOOKS B, CUSTOMERS C
WHERE O.ORDER# = I.ORDER#
AND I.ISBN = B.ISBN
AND O.CUSTOMER# = C.CUSTOMER#
AND C.LASTNAME = 'LUCAS'
ORDER BY O.ORDERDATE, PROFIT DESC;

--HANDS-ON 5:B JOIN KEYWORD APPROACH //COMP122 301242419 CARL KEVIN GASAL
SELECT O.ORDERDATE, I.ISBN, I.QUANTITY, (I.PAIDEACH - B.COST) * I.QUANTITY AS PROFIT, C.LASTNAME
FROM ORDERS O
JOIN ORDERITEMS I ON O.ORDER# = I.ORDER#
JOIN BOOKS B ON I.ISBN = B.ISBN
JOIN CUSTOMERS C ON O.CUSTOMER# = C.CUSTOMER#
WHERE C.LASTNAME = 'LUCAS'
ORDER BY O.ORDERDATE, PROFIT DESC;

--HANDS-ON 6:A TRADITIONAL APPROACH  //COMP122 301242419 CARL KEVIN GASAL
SELECT BOOKS.TITLE, AUTHOR.LNAME
FROM BOOKS, AUTHOR, BOOKAUTHOR
WHERE BOOKS.ISBN = BOOKAUTHOR.ISBN
  AND AUTHOR.AUTHORID = BOOKAUTHOR.AUTHORID
  AND AUTHOR.LNAME LIKE '%ADAMS%';

--HANDS-ON 6:B JOIN KEYWORD APPROACH //COMP122 301242419 CARL KEVIN GASAL
SELECT BOOKS.TITLE, AUTHOR.LNAME
FROM BOOKS
JOIN BOOKAUTHOR ON BOOKS.ISBN = BOOKAUTHOR.ISBN
JOIN AUTHOR ON AUTHOR.AUTHORID = BOOKAUTHOR.AUTHORID
WHERE AUTHOR.LNAME LIKE '%ADAMS%';

--HANDS-ON 7:A TRADITIONAL APPROACH  //COMP122 301242419 CARL KEVIN GASAL
SELECT PROMOTION.GIFT
FROM BOOKS
JOIN PROMOTION
ON BOOKS.RETAIL >= PROMOTION.MINRETAIL
AND BOOKS.RETAIL <= PROMOTION.MAXRETAIL
WHERE BOOKS.TITLE = 'SHORTEST POEMS';

--HANDS-ON 7:B JOIN KEYWORD APPROACH //COMP122 301242419 CARL KEVIN GASAL
SELECT PROMOTION.GIFT
FROM BOOKS
JOIN PROMOTION
ON BOOKS.RETAIL BETWEEN PROMOTION.MINRETAIL AND PROMOTION.MAXRETAIL
WHERE BOOKS.TITLE = 'SHORTEST POEMS';

--HANDS-ON 8:A TRADITIONAL APPROACH  //COMP122 301242419 CARL KEVIN GASAL
SELECT DISTINCT a.LNAME, a.FNAME
FROM CUSTOMERS c, ORDERS o, ORDERITEMS oi, BOOKS b, BOOKAUTHOR ba, AUTHOR a
WHERE c.LASTNAME = 'NELSON' AND c.FIRSTNAME = 'BECCA'
AND c.CUSTOMER# = o.CUSTOMER#
AND o.ORDER# = oi.ORDER#
AND oi.ISBN = b.ISBN
AND b.ISBN = ba.ISBN
AND ba.AUTHORID = a.AUTHORID;

--HANDS-ON 8:B JOIN KEYWORD APPROACH //COMP122 301242419 CARL KEVIN GASAL
SELECT DISTINCT a.LNAME, a.FNAME
FROM CUSTOMERS c
JOIN ORDERS o ON c.CUSTOMER# = o.CUSTOMER#
JOIN ORDERITEMS oi ON o.ORDER# = oi.ORDER#
JOIN BOOKS b ON oi.ISBN = b.ISBN
JOIN BOOKAUTHOR ba ON b.ISBN = ba.ISBN
JOIN AUTHOR a ON ba.AUTHORID = a.AUTHORID
WHERE c.LASTNAME = 'NELSON' AND c.FIRSTNAME = 'BECCA';

--HANDS-ON 9:A TRADITIONAL APPROACH  //COMP122 301242419 CARL KEVIN GASAL
SELECT B.ISBN, B.TITLE, B.PUBDATE, B.PUBID, B.COST, B.RETAIL, B.DISCOUNT, B.CATEGORY, O.ORDER#, C.STATE
FROM BOOKS B, ORDERITEMS OI, ORDERS O, CUSTOMERS C
WHERE B.ISBN = OI.ISBN(+)
AND OI.ORDER# = O.ORDER#(+)
AND O.CUSTOMER# = C.CUSTOMER#(+);
--HANDS-ON 9:B JOIN KEYWORD APPROACH //COMP122 301242419 CARL KEVIN GASAL
SELECT B.ISBN, B.TITLE, B.PUBDATE, B.PUBID, B.COST, B.RETAIL, B.DISCOUNT, B.CATEGORY, O.ORDER#, C.STATE
FROM BOOKS B
LEFT JOIN ORDERITEMS OI ON B.ISBN = OI.ISBN
LEFT JOIN ORDERS O ON OI.ORDER# = O.ORDER#
LEFT JOIN CUSTOMERS C ON O.CUSTOMER# = C.CUSTOMER#;

--HANDS-ON 10:A TRADITIONAL APPROACH  //COMP122 301242419 CARL KEVIN GASAL

--HANDS-ON 10:B JOIN KEYWORD APPROACH //COMP122 301242419 CARL KEVIN GASAL



